#!/usr/bin/env python3
"""
scylla_auto_fix.py - Scylla IAT自动修复工具 v1.0
自动化执行Scylla的IAT修复流程

用法:
    python scylla_auto_fix.py --target "BlackMamba.exe" --dump "dumped.exe"
    python scylla_auto_fix.py --target "BlackMamba.exe" --dump "dumped.exe" --output "fixed.exe"
    python scylla_auto_fix.py --list-processes
"""

import argparse
import os
import sys
import subprocess
import json
import time
from pathlib import Path

class ScyllaAutoFix:
    """Scylla IAT自动修复工具"""
    
    VERSION = "1.0.0"
    
    def __init__(self, target_name, dump_path, output_path=None):
        self.target_name = target_name
        self.dump_path = dump_path
        self.output_path = output_path or dump_path.replace(".exe", "_fixed.exe")
        self.scylla_path = self._find_scylla()
        self.logs = []
        
    def log(self, level, message):
        """记录日志"""
        from datetime import datetime
        timestamp = datetime.now().strftime("%H:%M:%S")
        log_entry = f"[{timestamp}] [{level}] {message}"
        self.logs.append(log_entry)
        print(log_entry)
    
    def _find_scylla(self):
        """查找Scylla可执行文件"""
        possible_paths = [
            r"C:\Tools\Scylla\Scylla_x64.exe",
            r"C:\Program Files\Scylla\Scylla_x64.exe",
            r"C:\Scylla\Scylla_x64.exe",
            r"C:\Tools\Scylla\Scylla.exe",
        ]
        for path in possible_paths:
            if os.path.exists(path):
                return path
        return None
    
    def check_environment(self):
        """检测环境"""
        self.log("INFO", "=" * 60)
        self.log("INFO", "Scylla IAT自动修复工具 v" + self.VERSION)
        self.log("INFO", "=" * 60)
        
        checks = {
            "scylla": False,
            "dump_file": False,
            "target_running": False,
        }
        
        # 1. 检测Scylla
        if self.scylla_path:
            self.log("INFO", f"    ✅ Scylla found: {self.scylla_path}")
            checks["scylla"] = True
        else:
            self.log("ERROR", "    ❌ Scylla not found")
            self.log("INFO", "    💡 请下载: https://github.com/NtQuery/Scylla")
            return checks
        
        # 2. 检测Dump文件
        if os.path.exists(self.dump_path):
            size = os.path.getsize(self.dump_path)
            self.log("INFO", f"    ✅ Dump file: {self.dump_path} ({size} bytes)")
            checks["dump_file"] = True
        else:
            self.log("ERROR", f"    ❌ Dump file not found: {self.dump_path}")
            return checks
        
        # 3. 检测目标进程
        try:
            import psutil
            for proc in psutil.process_iter(['pid', 'name']):
                if self.target_name.lower() in proc.info['name'].lower():
                    self.log("INFO", f"    ✅ Target running: {proc.info['name']} (PID: {proc.info['pid']})")
                    checks["target_running"] = True
                    self.target_pid = proc.info['pid']
                    break
        except ImportError:
            self.log("WARN", "    ⚠️  psutil not installed")
        
        if not checks["target_running"]:
            self.log("WARN", "    ⚠️  Target not running - IAT修复需要目标进程内存状态")
        
        return checks
    
    def generate_scylla_script(self):
        """生成Scylla自动化脚本"""
        # Scylla支持命令行参数
        script = f"""@echo off
REM Scylla IAT Auto-Fix Script
REM Generated by ScyllaAutoFix v{self.VERSION}

echo [*] Starting Scylla IAT Auto-Fix...
echo [*] Target: {self.target_name}
echo [*] Dump: {self.dump_path}
echo [*] Output: {self.output_path}

"{self.scylla_path}" \
    /target:"{self.target_name}" \
    /dump:"{self.dump_path}" \
    /output:"{self.output_path}" \
    /autoiat \
    /autofix

if %errorlevel% == 0 (
    echo [+] IAT Fix Complete!
    echo [+] Output: {self.output_path}
) else (
    echo [-] IAT Fix Failed!
    echo [-] Please check Scylla output
)

pause
"""
        return script
    
    def perform_fix(self):
        """执行IAT修复"""
        self.log("INFO", "[*] 执行IAT自动修复...")
        
        # 生成批处理脚本
        bat_script = self.generate_scylla_script()
        bat_path = f"scylla_fix_{self.target_name}.bat"
        
        with open(bat_path, 'w', encoding='utf-8') as f:
            f.write(bat_script)
        
        self.log("INFO", f"    ✅ 批处理脚本已生成: {bat_path}")
        
        # 提示手动执行或自动执行
        self.log("INFO", "    执行方式:")
        self.log("INFO", f"    1. 手动执行: 双击 {bat_path}")
        self.log("INFO", f"    2. 命令执行: {bat_path}")
        
        # 尝试自动执行
        try:
            self.log("INFO", "    尝试自动执行Scylla...")
            cmd = [
                str(self.scylla_path), 
                f"/target:{self.target_name}",
                f"/dump:{self.dump_path}",
                f"/output:{self.output_path}",
                "/autoiat"
            ]
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=60
            )
            
            if result.returncode == 0:
                self.log("INFO", "    ✅ Scylla IAT修复成功!")
                return True
            else:
                self.log("WARN", "    ⚠️  Scylla自动执行失败，请使用批处理脚本")
                self.log("INFO", f"    错误输出: {result.stderr[:200]}")
                return False
                
        except Exception as e:
            self.log("WARN", f"    ⚠️  自动执行异常: {str(e)}")
            self.log("INFO", "    请使用生成的批处理脚本手动执行")
            return False
    
    def verify_fix(self):
        """验证修复结果"""
        self.log("INFO", "[*] 验证IAT修复结果...")
        
        if not os.path.exists(self.output_path):
            self.log("ERROR", "    ❌ 输出文件不存在")
            return False
        
        # 检查文件大小
        size = os.path.getsize(self.output_path)
        self.log("INFO", f"    ✅ 输出文件: {self.output_path} ({size} bytes)")
        
        # 使用PE-bear或CFF Explorer验证
        self.log("INFO", "    验证方式:")
        self.log("INFO", "    1. 使用PE-bear打开输出文件")
        self.log("INFO", "    2. 检查导入表是否完整")
        self.log("INFO", "    3. 验证所有API地址是否正确")
        
        return True
    
    def run(self):
        """执行完整修复流程"""
        self.log("INFO", "=" * 60)
        self.log("INFO", "开始Scylla IAT自动修复")
        self.log("INFO", "=" * 60)
        
        # 环境检测
        env = self.check_environment()
        if not all(env.values()):
            self.log("ERROR", "环境检测失败，请修复上述问题")
            return False
        
        # 执行修复
        if self.perform_fix():
            self.verify_fix()
        
        self.log("INFO", "=" * 60)
        self.log("INFO", "Scylla IAT修复流程完成")
        self.log("INFO", "=" * 60)
        
        return True

def list_processes():
    """列出所有进程"""
    try:
        import psutil
        print("[*] 运行中的进程:")
        for proc in psutil.process_iter(['pid', 'name']):
            print(f"    {proc.info['pid']:6d} {proc.info['name']}")
    except ImportError:
        print("[!] psutil未安装")
        print("    pip install psutil")

def main():
    parser = argparse.ArgumentParser(
        description="Scylla IAT自动修复工具 v1.0",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
示例:
    # 完整修复流程
    python scylla_auto_fix.py --target "BlackMamba.exe" --dump "dumped.exe"
    
    # 指定输出路径
    python scylla_auto_fix.py --target "BlackMamba.exe" --dump "dumped.exe" --output "fixed.exe"
    
    # 列出进程
    python scylla_auto_fix.py --list-processes
        """
    )
    
    parser.add_argument("--target", "-t", help="目标进程名")
    parser.add_argument("--dump", "-d", help="Dump文件路径")
    parser.add_argument("--output", "-o", help="输出文件路径")
    parser.add_argument("--list-processes", action="store_true", help="列出所有进程")
    
    args = parser.parse_args()
    
    if args.list_processes:
        list_processes()
        return
    
    if not args.target or not args.dump:
        print("Error: 请指定目标进程名和Dump文件路径")
        parser.print_help()
        return
    
    # 创建修复工具实例
    fixer = ScyllaAutoFix(
        target_name=args.target,
        dump_path=args.dump,
        output_path=args.output
    )
    
    # 执行修复
    fixer.run()

if __name__ == "__main__":
    main()
